# Markdown
This is a markdown cell where we write instructions and math formulas. **Double click** to edit and **press Run** to see the formatted texts.

# Load and Save Notebook
To load a note book, just go to "File" and navigate to "Open...". Use keyboard shortcut **Cmd/Ctrl+s** to save the file. You will be saving a checkpoint as well if you use this keyboard shortcut. You can click on "File" on the menu bar and select an option to revert to a certain checkpoint. Jupyter Notebook will also autosave your file every 120s, but it's still a good practice to press **Cmd/Ctrl+s** often when you write programs. 

# Code Blocks
Below will be an example of a Python code block. Hit **Run** to run the block.

In [1]:
print("Hello world!")

Hello world!


You can also hit **Run All** in "Cell" menu. To run every blocks. 

In [2]:
print("Hello world, again!")

Hello world, again!


# Python Programming
We have finished Jupyter Notebook introduction. Below we will start Python Programming.

## Importing Libraries
For the lab, we will be using different libraries. This is how you do it in Python.

In [3]:
import pandas as pd
import numpy as np

By importing pandas as pd, you can use the shorthand `pd` when you need to use pandas. The same method applies to `np`.

## NumPy Tutorial
Below we show you a few ways to create arrays.

In [4]:
# Create a basic array
x = np.array([0, 1, 2, 3])
print("x:\n", x)

# Create a 2D array
y = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7]])
print("y:\n", y)

# Create a 3 by 4 empty array
z = np.zeros((3, 4))
print("z:\n", z)

# Create a 5 by 5 array filled with 1s
a = np.ones((5, 5))
print("a:\n", a)

# Create a sequence of numbers, note the array does not include 20
b = np.arange(0, 20, 2)
print("b:\n", b)

# Use reshape to change the dimention of the array
c = np.arange(0, 20, 2, dtype=float).reshape(2, 5)
print("c:\n", c)

# Create a random 6 by 3 array with value between [0, 1).
d = np.random.rand(6, 3)
print("d:\n", d)
    
    # This creates random values ranging between [1, 4).
d = d*3 + 1
print("New d:\n", d)

# Operations
e = d + 10
print("e:\n", e)

x:
 [0 1 2 3]
y:
 [[0 1 2 3]
 [4 5 6 7]]
z:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
a:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
b:
 [ 0  2  4  6  8 10 12 14 16 18]
c:
 [[ 0.  2.  4.  6.  8.]
 [10. 12. 14. 16. 18.]]
d:
 [[0.54133542 0.30350381 0.6017118 ]
 [0.66899163 0.27073733 0.35937466]
 [0.54862826 0.64123846 0.75724995]
 [0.08144821 0.59842252 0.41777302]
 [0.73090993 0.19381552 0.63867736]
 [0.05304834 0.8260059  0.57949976]]
New d:
 [[2.62400627 1.91051143 2.80513541]
 [3.00697489 1.812212   2.07812399]
 [2.64588477 2.92371537 3.27174984]
 [1.24434464 2.79526756 2.25331906]
 [3.19272978 1.58144657 2.91603209]
 [1.15914501 3.47801769 2.73849927]]
e:
 [[12.62400627 11.91051143 12.80513541]
 [13.00697489 11.812212   12.07812399]
 [12.64588477 12.92371537 13.27174984]
 [11.24434464 12.79526756 12.25331906]
 [13.19272978 11.58144657 12.91603209]
 [11.15914501 13.47801769 12.73849927]]


**Now it's your turn.** 

**To-do:**
1. Create and print out an empty array with dimensions of 15 by 29.
2. From the 0 array you created, make it to an ones array without using np.ones. Print out the array.
3. Create an 8 by 9 array with values between $[5, 11)$. Note that 11 is excluded. Print out the array.



In [5]:
### Insert code below ###

# Q1 - Create and print out a 15 by 29 empty array.
arr0 = np.zeros((15, 29))
print("1. Empty array 'arr0' with dimensions of 15 by 29:\n", arr0)

# Q2 - Use operations to convert arr from empty array to ones array
arr0 = arr0 + 1
print("2. Converted 'arr0' into a ones array:\n", arr0)

# Q3
# Create a random 8 by 9 array with value between [0, 1).
arr1 = np.random.rand(8, 9)
# Use operations to create random values ranging between [5, 11).
arr1 = arr1*6 + 5
print("3. 8 by 9 array 'arr1' with values between [5,11):\n", arr1)


1. Empty array 'arr0' with dimensions of 15 by 29:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.

## Pandas Tutorial
### Create Data Frame
Pandas is a data frame that will be used to handel our data.

In [6]:
# Create a data frame from numpy array
df_1 = pd.DataFrame(y, columns=['col 1', 'col 2', 'col 3', 'col 4'])
print("df_1:\n", df_1, '\n')
print("------------------------------------") # for readability only

# You can also use display() to make the dataframe looks nicer at the output
print("df_1 using display:")
display(df_1)
print("------------------------------------")

# Create a data frame with strings
data_2 = {'Aminal': ['Dog', 'Cat'], 'Color': ['Yellow', 'Pink'], 'Age': [1, 3]}
df_2 = pd.DataFrame(data=data_2)
print("df_2:\n", df_2, '\n')
print("------------------------------------")

# Print the type of the data. Notice that Age is int
df_2.dtypes

df_1:
    col 1  col 2  col 3  col 4
0      0      1      2      3
1      4      5      6      7 

------------------------------------
df_1 using display:


col 1  col 2  col 3  col 4
0      0      1      2      3
1      4      5      6      7

------------------------------------
df_2:
   Aminal   Color  Age
0    Dog  Yellow    1
1    Cat    Pink    3 

------------------------------------


Aminal    object
Color     object
Age        int64
dtype: object

#### Now it's your turn. 

**To-do:**

1. Create a data frame containing demographics of you and your 2 friends. The data frame should be 3 by 4. The columns will be 'Name', 'Age', 'Height', 'Hobby'. You can make up data if you like. Print or display the result. 

In [7]:
### Insert your code below ###

# Create a dictionary with demographics for three people
friends = {'Name': ['Madhu', 'Rachel', 'Ross'], 'Age': [21,24,26], 'Height': ["5'4\"","5'5\"","6'1\""],
          'Hobby': ['Tennis', 'Shopping', 'Museums']}

# Create a data frame using "friends" dictionary
demographics = pd.DataFrame(data=friends)

# Display dataframe
print("Dataframe (3 by 4) containing demographics of three individuals:")
display(demographics)


Dataframe (3 by 4) containing demographics of three individuals:


Name  Age Height     Hobby
0   Madhu   21   5'4"    Tennis
1  Rachel   24   5'5"  Shopping
2    Ross   26   6'1"   Museums

### Modify Data Frame
Notice that when you use `=`, you are not copying data frame. You are just saying that `df_3` is now referring to the same data frame as `df_1`. If you change values in `df_3` you will change the values in `df_1` too, since both are referring to the same dataframe. Also notice that every time you click **Run** in this block, the values in `'col 1'` changes.  

In [8]:
# Add a new column
df_2['Weight'] = [89, 60]
print("New df_2:")
display(df_2)
print("------------------------------------")

# Special thing to take notice
df_3 = df_1
df_3['col 1'] = df_3['col 1'] - 1
print("df_3:")
display(df_3)
print("df_1:")
display(df_1)


New df_2:


Aminal   Color  Age  Weight
0    Dog  Yellow    1      89
1    Cat    Pink    3      60

------------------------------------
df_3:


col 1  col 2  col 3  col 4
0     -1      1      2      3
1      3      5      6      7

df_1:


col 1  col 2  col 3  col 4
0     -1      1      2      3
1      3      5      6      7

### Print Specific Data
Here we use `.loc`, `.at` to obtain the cell values by providing the **labels** (e.g. 'Age', 'Weight'). For rows, since we do not create labels for them the defaults will be 0, 1, 2, 3...etc. We use `.iloc`, `.iat` to obtain the cell values by prividing the indicies (positions) of the rows and columns. 

In [9]:
# Few ways to view the values

# Create a data frame based on data_2; the values are copied
df_4 = pd.DataFrame(data=data_2)
print("df_4:")
display(df_4)
print("------------------------------------")

# Selection by Label
    # Getting the scalar value
dog_age = df_4.loc[0, 'Age']
print("Age of Dog:", dog_age, '\n')
print("------------------------------------")

    # Getting the whole column 
aminals_age = df_4.loc[:, ['Age']]
print("Age Column:")
display(aminals_age)
print("------------------------------------")

    # Faster way to get a scalar
cat_age = df_4.at[1, 'Age']
print("Age of Cat:", cat_age, '\n')
print("------------------------------------")

# Selection by position
    # Selecting Row based on row number
dog = df_4.iloc[0]
print("Dog row:")
print(dog, '\n')
print("------------------------------------")

    # Selecting Col based on col number
animals_age_p = df_4.iloc[:, 2]
print("Animals' age:")
print(animals_age_p, '\n')
print("------------------------------------")
    # Selecting cell based on col number
cat_age_p = df_4.iat[1, 2]
print("Age of Cat: ", cat_age_p)

df_4:


Aminal   Color  Age
0    Dog  Yellow    1
1    Cat    Pink    3

------------------------------------
Age of Dog: 1 

------------------------------------
Age Column:


Age
0    1
1    3

------------------------------------
Age of Cat: 3 

------------------------------------
Dog row:
Aminal       Dog
Color     Yellow
Age            1
Name: 0, dtype: object 

------------------------------------
Animals' age:
0    1
1    3
Name: Age, dtype: int64 

------------------------------------
Age of Cat:  3


#### Now it's your turn.
**To-do:**

1. Add a new **row** to your **demographics** data frame. The new row will contain information of another friend. *Note that we haven't taught you how to do so but you should be able to find resources online easily.* Print/display the data frame.
2. Print all the information (whole row) about you using `.loc`.
3. Print the 'Name' of your second friend using `.iat`.


In [10]:
### Insert your code below ###


# Dictionary containing new information of another friend
new_friend = {'Name': 'Monica', 'Age': 24, 'Height': "5'4\"", 'Hobby': 'Cooking'}

# Add new row (information from dictionary new_friend) to demographics dataframe 
demographics = demographics.append(new_friend, ignore_index = True)

print("Demographics data frame with new row with information of another friend appended:")
display(demographics)
print("------------------------------------\n")

# Select entire row for label of the index (0) using .loc
my_information = demographics.loc[0]
print("My information (whole row) using .loc:")
print(my_information, '\n')

print("------------------------------------\n")

# Selecting cell based on row/column pair (row=2, column=0)
name_friend2 = demographics.iat[2, 0]
print("Name of Second Friend using .iat: ", name_friend2, "\n")
print("------------------------------------")


Demographics data frame with new row with information of another friend appended:


Name  Age Height     Hobby
0   Madhu   21   5'4"    Tennis
1  Rachel   24   5'5"  Shopping
2    Ross   26   6'1"   Museums
3  Monica   24   5'4"   Cooking

------------------------------------

My information (whole row) using .loc:
Name       Madhu
Age           21
Height      5'4"
Hobby     Tennis
Name: 0, dtype: object 

------------------------------------

Name of Second Friend using .iat:  Ross 

------------------------------------


**Congradulation on finishing the tutorial! Now you can move on to the next step of the lab.**